Update output

diff --git a/bin/rc-common-emacs-leuven b/bin/rc-common-emacs-leuven
--- a/bin/rc-common-emacs-leuven
+++ b/bin/rc-common-emacs-leuven
@@ -49,7 +49,7 @@ export VISUAL="$EDITOR"
 # Cd to the directory of the current buffer in Emacs.
 cde() {
     if ! command -v emacsclient > /dev/null 2>&1; then
-        printf >&2 "Error: emacsclient not found.\n"
+        printf >&2 "Error: emacsclient command not found.\n"
         printf >&2 "Please install Emacsclient and ensure the binary is in your PATH.\n"
         return 2
     fi
